version: "3.9"

services:
  

  db:
    image: postgres:13
    command: -c 'max_connections=5000'
  
    environment:
      - POSTGRES_USER=${PROD_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PROD_POSTGRES_PASSWORD}
      - POSTGRES_DB=${PROD_POSTGRES_DB}
      - DATABASE_HOST=${PROD_DATABASE_HOST}
      - DATABASE_PORT=${PROD_DATABASE_PORT}
    
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$PROD_POSTGRES_USER\" -d \"$PROD_POSTGRES_DB\""]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - database


volumes:
  data:

networks:
  database:
    driver: bridge